Use UTF8 coding if wide characters are used
Otherwise, throw an exception like:

Traceback (most recent call last):
  File "./tests/sendmail-ntlmv2.py", line 93, in <module>
    conn.sendmail(FROMADDR, toaddrs, hdr + msg)
  File "/usr/lib/python3.8/smtplib.py", line 859, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 77-78: ordinal not in range(128)

Signed-off-by: Ping-Ke Shih <pkshih@realtek.com>